### ISSUE TITLE
What would a JVM implementation of the Reviews service look like?

### ISSUE THREAD

**Issue by erikhh** [apollographql/federation-jvm#83]
Hello,

I'm trying to get a started with federation, our services are generally all in Java. As a start I'm trying to mimic the apollo federation example services from here: https://www.apollographql.com/docs/federation/implementing-services/ but the JVM equivalent.

I'm having a hard time getting my head around it all. 

Here's my schema for the Reviews service:
```
type Review @key(fields: "id") {
  id: ID!
  body: String
  author:String
  product: Product
}

extend type Product @key(fields: "upc") {
  upc: String! @external
  reviews: [Review]
}
``` 

And in my code I load that up like so:
```java
  Federation.transform(sdl, runtimeWiring)
      .resolveEntityType(entityTypeResolver)
      .fetchEntities(entityFetcher)
      .build();
```

But then I get this error:
```
graphql.schema.idl.errors.SchemaProblem: errors=[The extension 'Product' type [@8:1] is missing its base underlying type]

	at com.apollographql.federation.graphqljava.Federation.transform(Federation.java:31) ~[federation-graphql-java-support-0.5.0.jar:na]
	at com.apollographql.federation.graphqljava.Federation.transform(Federation.java:43) ~[federation-graphql-java-support-0.5.0.jar:na]
```

And if I leave the `extends` out. The service will start, but the gateway complains that the type Product is defined twice.

So, now I'm confused as to what should it be then?

**Comment by erikhh** [comment]
For anybody else coming here to look for help.
I've found a complete example at https://github.com/vinaybedre/java-graphql-federation-starter
