### ISSUE TITLE
ClassNotFoundException: graphql.execution.ExecutionPath

### ISSUE THREAD

**Issue by giuseppeparello** [apollographql/federation-jvm#86]
try to using FederatedTracingInstrumentation.class from federation-graphql-java-support inside a quarkus 1.10.5.Final microservice that use graphql-java 16.1 (instead of 15.0 version ) these exception is throwed:
Caused by: java.lang.ClassNotFoundException: graphql.execution.ExecutionPath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:412)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
	... 24 more

**Comment by setchy** [comment]
This is because in 16.1 ExecutionPath was renamed to ResultPath.  

The federation-jvm library will need to be updated and released

**Comment by setchy** [comment]
@giuseppeparello - v0.6.0 was released yesterday

**Comment by sachindshinde** [comment]
The rename issue should indeed be fixed in the latest release.
